### ISSUE TITLE
respeten los codigos de INDEC para las provincias y los departamentos

### ISSUE THREAD

**Issue by aaizemberg** [shipupi/vacunas-argentina-covid#1]
Son 2 números para provincia y 3 para el depto.
El código completo para identificar un Departamento son los 2 de la provincia + los 3 del depto, concatenado y son 5 numeros. Por ej. 02015 (estaría indicando, la comuna 15 de CABA)

Ej.

02 --> CABA
06 --> Buenos Aires
... etc

**Comment by shipupi** [comment]
Fixed in  40c366749f531c1e05fd2fe298557b90ed35b86c
